"""new model

Revision ID: 1840a48dc3c8
Revises: 5ad05cfe51
Create Date: 2016-11-30 19:43:30.998687

"""

# revision identifiers, used by Alembic.
revision = '1840a48dc3c8'
down_revision = '5ad05cfe51'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
