"""add userid

Revision ID: 304621c29b32
Revises: 506da777725e
Create Date: 2016-11-19 18:12:48.452060

"""

# revision identifiers, used by Alembic.
revision = '304621c29b32'
down_revision = '506da777725e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('userid', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'userid')
    ### end Alembic commands ###
