"""init

Revision ID: 3281d538bc59
Revises: None
Create Date: 2016-12-16 08:20:32.103510

"""

# revision identifiers, used by Alembic.
revision = '3281d538bc59'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
