"""back

Revision ID: 38939c5ba2cc
Revises: db0335bbc66
Create Date: 2016-12-20 12:24:02.797184

"""

# revision identifiers, used by Alembic.
revision = '38939c5ba2cc'
down_revision = 'db0335bbc66'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
