"""user change

Revision ID: 42c899fdbb20
Revises: 4d0b03ec1499
Create Date: 2016-12-22 00:08:36.094128

"""

# revision identifiers, used by Alembic.
revision = '42c899fdbb20'
down_revision = '4d0b03ec1499'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
