"""password change

Revision ID: 4800ad89c7d4
Revises: 38939c5ba2cc
Create Date: 2016-12-21 16:58:19.902931

"""

# revision identifiers, used by Alembic.
revision = '4800ad89c7d4'
down_revision = '38939c5ba2cc'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('readings', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('password', sa.String(length=128), nullable=True))
    op.drop_column('users', 'password_hash')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', mysql.VARCHAR(length=128), nullable=True))
    op.drop_column('users', 'password')
    op.drop_column('readings', 'user_id')
    ### end Alembic commands ###
