"""password hange

Revision ID: 4d0b03ec1499
Revises: 4800ad89c7d4
Create Date: 2016-12-21 17:32:59.366689

"""

# revision identifiers, used by Alembic.
revision = '4d0b03ec1499'
down_revision = '4800ad89c7d4'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=True))
    op.drop_column('users', 'password')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', mysql.VARCHAR(length=128), nullable=True))
    op.drop_column('users', 'password_hash')
    ### end Alembic commands ###
