"""new model

Revision ID: 5ad05cfe51
Revises: 22db450c605
Create Date: 2016-11-30 19:16:32.311015

"""

# revision identifiers, used by Alembic.
revision = '5ad05cfe51'
down_revision = '22db450c605'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sentence_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sentence_id', sa.Integer(), nullable=True),
    sa.Column('phrase', sa.Text(), nullable=True),
    sa.Column('grammar', sa.Text(), nullable=True),
    sa.Column('translation', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['sentence_id'], ['sentences.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('word_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=True),
    sa.Column('Chinese', sa.String(length=64), nullable=True),
    sa.Column('Phonogram', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('notes')
    op.add_column(u'words', sa.Column('sentence_id', sa.Integer(), nullable=True))
    op.add_column(u'words', sa.Column('word_body', sa.String(length=32), nullable=True))
    op.drop_column(u'words', 'word')
    op.drop_column(u'words', 'Phonogram')
    op.drop_column(u'words', 'Chinese')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'words', sa.Column('Chinese', mysql.VARCHAR(length=64), nullable=True))
    op.add_column(u'words', sa.Column('Phonogram', mysql.VARCHAR(length=32), nullable=True))
    op.add_column(u'words', sa.Column('word', mysql.VARCHAR(length=32), nullable=True))
    op.drop_column(u'words', 'word_body')
    op.drop_column(u'words', 'sentence_id')
    op.create_table('notes',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('phrase', mysql.TEXT(), nullable=True),
    sa.Column('grammar', mysql.TEXT(), nullable=True),
    sa.Column('translation', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('word_notes')
    op.drop_table('sentence_notes')
    ### end Alembic commands ###
