"""one to one

Revision ID: db0335bbc66
Revises: 3281d538bc59
Create Date: 2016-12-19 23:40:00.946133

"""

# revision identifiers, used by Alembic.
revision = 'db0335bbc66'
down_revision = '3281d538bc59'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
